name: x86-Darwin

on: 
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          brew update
          brew install llvm
          pip3 install lit
      - name: Build type-correct + run tests
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build && cd build
          cmake -DCT_Clang_INSTALL_DIR=/usr/local/opt/llvm/  ../
          make -j2
          lit test/
